language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - "python setup.py install"
  - "pip install coveralls"
script:
  - "nosetests --with-coverage --cover-package=kpy"
after_success:
  - coveralls
